public class LimitClass {
    public static void method1(){
        System.debug('Limits.getLimitAggregateQueries - '+ Limits.getLimitAggregateQueries());
        System.debug('Limits.getCallouts - '+ Limits.getCallouts());
        System.debug('Limits.getHeapSize - '+ Limits.getHeapSize());
        System.debug('Limits.getDMLRows - '+ Limits.getDMLRows());
        System.debug('Limits.getDMLStatements - '+ Limits.getDMLStatements());
        System.debug('Limits.getEmailInvocations - '+ Limits.getEmailInvocations());
        System.debug('Limits.getLimitEmailInvocations - '+ Limits.getLimitEmailInvocations());
        System.debug('Limits.getFutureCalls - '+ Limits.getFutureCalls());
        System.debug('Limits.getLimitHeapSize - '+ Limits.getLimitHeapSize());
        System.debug('Limits.getLimitQueryRows - '+ Limits.getLimitQueryRows());
        }

}